services:
  python-misc:
    container_name: python-misc
    restart: unless-stopped
    build:
      context: ./Modules
      dockerfile: Dockerfile
    image: python-misc
    volumes:
      - ./Modules/:/app/
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.docker.env
